version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel and RBE credential
          command: |
            # Install bazel
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

            # Install RBE credential
            bazel run @graknlabs_build_tools//ci:install-bazel-rbe-credential

  run-bazel-rbe:
    parameters:
      command:
        type: string
      steps:
        - run:
            command: |
              bazel run @graknlabs_build_tools//ci:run-bazel-rbe << parameters.command >>

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run: bazel run @graknlabs_build_tools//checkstyle:test-coverage
      - run-bazel-rbe:
          command: bazel build //...

  test:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel test //... --test_size_filters=small --test_output=errors
      - run-bazel-rbe:
          command: bazel test //... --test_size_filters=medium,large,enormous --test_output=errors

  sync-dependencies:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run:
          name: Sync docs:development to the latest client-java:master
          command: |
            bazel run @graknlabs_build_tools//ci:sync-dependencies -- --source client-java:master --targets docs:development

workflows:
  client-java:
    jobs:
      - build
      - test
      - sync-dependencies:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
